name: 'Neo-Brutalist Release Banner Generator'
description: 'Generates a neo-brutalist style release badge for GitHub releases'

branding:
  icon: 'tag'
  color: 'yellow'

inputs:
  version:
    description: 'Release version'
    required: true
  body:
    description: 'Release body text (changelog)'
    required: true
  repo_url:
    description: 'Repository URL'
    required: true
  project_name:
    description: 'Project name (defaults to repository name if not provided)'
    required: false
  project_description:
    description: 'Short description of the project to display under the project name'
    required: false
  theme:
    description: 'Theme name to use for styling (e.g. "default")'
    default: 'default'
  logo:
    description: 'Logo URL to display in the badge'
    required: false
  debug:
    description: 'Enable debug mode to save HTML output'
    required: false
    default: 'false'
  strict_style:
    description: 'If true, will throw an error when fonts or styles are not available'
    required: false
    default: 'true'
  output:
    description: 'Output file path'
    default: 'release.png'

runs:
  using: 'composite'
  steps:
    - name: Generate Release Banner
      uses: docker://ghcr.io/automationd/action-brutalease:${{ github.action_ref || 'latest' }}
      env:
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_BODY: ${{ inputs.body }}
        INPUT_REPO_URL: ${{ inputs.repo_url }}
        INPUT_PROJECT_NAME: ${{ inputs.project_name }}
        INPUT_PROJECT_DESCRIPTION: ${{ inputs.project_description }}
        INPUT_THEME: ${{ inputs.theme }}
        INPUT_LOGO: ${{ inputs.logo }}
        INPUT_DEBUG: ${{ inputs.debug }}
        INPUT_STRICT_STYLE: ${{ inputs.strict_style }}
        INPUT_OUTPUT: ${{ inputs.output }}
