name: 'Neo-Brutalist Release Banner Generator'
description: 'Generates a neo-brutalist style release badge for GitHub releases'

branding:
  icon: 'tag'
  color: 'yellow'

inputs:
  version:
    description: 'Release version'
    required: true
  body:
    description: 'Release body text (changelog)'
    required: true
  repo_url:
    description: 'Repository URL'
    required: true
  project_name:
    description: 'Override the project name displayed on the badge'
    required: false
  project_description:
    description: 'Add a short description below the project name'
    required: false
  theme:
    description: 'Theme name, YAML string, or path to YAML file for customizing appearance'
    required: false
    default: 'default'
  debug:
    description: 'Enable debug mode to save HTML output (true/false)'
    required: false
    default: 'false'
  strict_style:
    description: 'Apply stricter CSS styling to prevent text overflow (true/false)'
    required: false
    default: 'false'
  output:
    description: 'The path where the generated image should be saved'
    required: true
    default: 'release.png'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/dimmkirr/action-brutalease:v1.0.9'
