name: Release

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

on:
  release:
    types:
      - published
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        id: push
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  generate-badge:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Generate Banner
        uses: ./
        with:
          version: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
          repo_url: ${{ github.repository }}
          output: release-banner.png
          project_name: Brutalease
          project_description: Neo-brutalist release banner
          logo: ${{ github.workspace }}/test/data/logo.png

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-banner
          path: release-banner.png

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: release-banner.png
          tag_name: ${{ github.event.release.tag_name }}

      - name: Update release description with image
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          IMAGE_URL: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/release-banner.png
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get current release body
          RELEASE_BODY=$(gh release view "$RELEASE_TAG" --json body -q .body)

          # Create a temporary file with the new release body
          echo -e "![Release Banner]($IMAGE_URL)\n\n$RELEASE_BODY" > new_body.md

          # Update the release with the new body
          gh release edit "$RELEASE_TAG" --notes-file new_body.md
